let num1 = prompt('Digite o primeiro número: ');
let num2 = prompt('Digite o segundo número: ');
let num3 = prompt('Digite o terceiro número: ');
let num4 = prompt('Digite o quarto número: ');
let num5 = prompt('Digite o quinto número: ');

let soma = (parseInt(num1)+ parseInt(num2) + parseInt(num3) + parseInt(num4) + parseInt(num5));

document.write(`Os números digitados foram ${num1}, ${num2}, ${num3}, ${num4} e ${num5} e suma soma é ${soma}`);